### ISSUE TITLE
Deployment working but not showing up in pull requests

### ISSUE THREAD

**Issue by richmccartney** [eliperelman/now-travis#1]
Hey @eliperelman, just wondering if there is any extra setup needed. I've gone through the steps stated in an example repo so I can understand everything. Travis builds my assets and tests and goes through now-travis and when checking my now.sh account I see the new instance but it's not showing on the PR.

Just to add I am not limited by the amount of instances. Any insight into what I might need to change?

**Comment by kentcdodds** [comment]
I'm also experiencing this. I modified `now-travis` to show logs and I'm seeing the `ghRepo.status` call is successful. Here's [a build](https://travis-ci.org/kentcdodds/glamorous-website/builds/238240423).

Would love to know how to use this. It's awesome!

**Comment by kentcdodds** [comment]
It appears that the commit that we're pushing the status to is not the commit that's being built. At least, it's not the one on the PR that's being built. I'm not sure what's going on here. Digging further.

**Comment by kentcdodds** [comment]
I worked it out ([with some help](https://twitter.com/kossnocorp/status/870190216807677953))! It's pretty simple! See #2
