### ISSUE TITLE
upgrade now CLI

### ISSUE THREAD

**Issue by kentcdodds** [eliperelman/now-travis#3]
I'm working on improving this package a bit and noticed that the version of now used in this project is very old. But the newest version doesn't export a CLI anymore. I think we should probably use now-client, but want to know what you think.

**Comment by eliperelman** [comment]
Yeah, I'm totally for any upgrades you want to propose. I wrote this when the now stuff was a bit younger, so I'm sure it could use some TLC.

**Comment by kentcdodds** [comment]
Ok, so [here's what I've come up with](https://github.com/kentcdodds/glamorous-website/blob/master/other/now-travis) that works in my project right now. It doesn't support an option to run only after all of travis runs are finished, but if I added that would you like me to just make a single big PR for all of those changes? Would probably be easier for me that way.

**Comment by eliperelman** [comment]
@kentcdodds yep, that works for me! Address as much in a single PR as you would like.

**Comment by kentcdodds** [comment]
I'm not using this anymore so I'll go ahead and close this issue. Thanks!
